schema_version = "1.0.0"

id = "pogo_blend"
version = "1.0.3"
name = "PogoBlend"
tagline = "An Add-on for creating Pogostuck Custom Maps using Blender"
maintainer = "gubFS"
copyright = ["2026 gubFS"]
type = "add-on"

website = "https://gubfs.github.io/pogo-blend/"

blender_version_min = "4.5.0"
blender_version_max = "5.0.0"

platforms = [
  "windows-x64",
  "macos-arm64",
  "linux-x64"
]

wheels = [
  "./wheels/xxhash-3.6.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/xxhash-3.6.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/xxhash-3.6.0-cp311-cp311-win_amd64.whl",
  "./wheels/pyyaml-6.0.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pyyaml-6.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/pyyaml-6.0.3-cp311-cp311-win_amd64.whl"
]

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Export files to Custom Maps folder"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
   "*.zip",
  "docs/",
  "app_template/",
  "!app_template.zip",
  "pogo_blend_asset_library/pogostuck.blend",
  "pogo_blend_asset_library/*.blend1",
  "README.md",
  "export_import/mdl_exporter/MDL7Format.txt",
  "build",
  "justfile"
]
